"use client";

import Link from "next/link";
import Image from "next/image";
import { useQuery } from "convex/react";
import { useUser } from "@clerk/nextjs";
import { Sparkles, Mic } from "lucide-react";
import { api } from "@/convex/_generated/api";
import InterviewCard from "@/components/InterviewCard";

export default function DashboardPage() {
  const { user } = useUser();
  const interviews = useQuery(api.interviews.list);

  return (
    <div className="flex flex-col gap-12">
      {/* Hero */}
      <section className="bg-surface-container border border-white/10 rounded-xl overflow-hidden flex flex-col md:flex-row items-stretch">
        <div className="p-8 md:p-12 flex-1 flex flex-col justify-center">
          <p className="label-caps text-primary mb-4 flex items-center gap-2">
            <Sparkles size={14} /> Welcome back{user?.firstName ? `, ${user.firstName}` : ""}
          </p>
          <h1 className="text-headline-xl text-on-surface mb-4">
            Get Interview-Ready with AI-Powered Practice &amp; Feedback
          </h1>
          <p className="text-body-md text-on-surface-variant mb-8 max-w-xl">
            Master your technical and behavioral interviews with real-time feedback, personalized
            coaching, and dynamic scenarios generated by your AI mentor.
          </p>
          <div className="flex gap-4 flex-wrap">
            <Link
              href="/interview/new"
              className="bg-primary text-on-primary font-bold py-3 px-6 rounded-md hover:brightness-110 transition-all active:scale-95 shadow-[0_0_20px_rgba(222,213,255,0.2)]"
            >
              Start Practice
            </Link>
            <a
              href="#interviews"
              className="border border-primary text-primary font-bold py-3 px-6 rounded-md hover:bg-primary/10 transition-all active:scale-95"
            >
              View My Interviews
            </a>
          </div>
        </div>
        <div className="w-full md:w-5/12 min-h-[260px] bg-surface-container-high relative flex items-center justify-center overflow-hidden">
          <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_center,rgba(195,181,253,0.25),transparent_70%)]" />
          <div className="relative flex items-center justify-center">
            <div className="absolute w-56 h-56 bg-primary/15 rounded-full blur-2xl pulse-ring" />
            <Image src="/logo.svg" alt="" width={160} height={160} className="relative z-10" />
          </div>
        </div>
      </section>

      {/* Interviews grid */}
      <section id="interviews">
        <h2 className="text-headline-lg text-on-surface mb-6">Your Interviews</h2>
        {interviews === undefined ? (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {Array.from({ length: 4 }).map((_, i) => (
              <div key={i} className="bg-surface-container rounded-xl border border-white/10 h-64 animate-pulse" />
            ))}
          </div>
        ) : interviews.length === 0 ? (
          <div className="bg-surface-container border border-white/10 rounded-xl p-12 flex flex-col items-center text-center gap-4">
            <div className="w-16 h-16 rounded-full bg-primary/10 border border-primary/30 flex items-center justify-center text-primary">
              <Mic size={28} />
            </div>
            <h3 className="text-headline-md text-on-surface">No interviews yet</h3>
            <p className="text-body-md text-on-surface-variant max-w-md">
              Create your first AI mock interview — pick a role, level, and tech stack, and start
              practicing in minutes.
            </p>
            <Link
              href="/interview/new"
              className="mt-2 bg-primary text-on-primary font-bold py-3 px-6 rounded-md hover:brightness-110 transition-all active:scale-95"
            >
              Create an Interview
            </Link>
          </div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {interviews.map((interview) => (
              <InterviewCard key={interview._id} interview={interview} />
            ))}
          </div>
        )}
      </section>
    </div>
  );
}
